export const AESTROIDID = 'AESTROIDID';
export const GET_ALL_ASTEROIDS='GET_ALL_ASTEROIDS';
// export const API_ERROR="API_ERROR";
// export const GET_ALL_ASTEROIDS_START='GET_ALL_ASTEROIDS_START';
// export const GET_ALL_ASTEROIDS_SUCCESS='GET_ALL_ASTEROIDS_SUCCESS';
